"""Activity parent_id nullable

Revision ID: 086db8a8858a
Revises: baad2660a54c
Create Date: 2025-08-12 13:07:51.384698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "086db8a8858a"
down_revision: Union[str, Sequence[str], None] = "baad2660a54c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activities", "parent_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "phones",
        "number",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phones",
        "number",
        existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=12),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "activities", "parent_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
