"""Organisation name index

Revision ID: 140ff0b4e653
Revises: e7320dd09d66
Create Date: 2025-08-12 19:16:46.184665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "140ff0b4e653"
down_revision: Union[str, Sequence[str], None] = "e7320dd09d66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "organisations_name_idx",
        "organisations",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.alter_column(
        "phones",
        "number",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phones",
        "number",
        existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=12),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_index(
        "organisations_name_idx",
        table_name="organisations",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
