"""Organisation building_id fk fix

Revision ID: baad2660a54c
Revises: 9c55ca8ede23
Create Date: 2025-08-12 11:22:42.674221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "baad2660a54c"
down_revision: Union[str, Sequence[str], None] = "9c55ca8ede23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("organisations_building_id_fkey"), "organisations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("organisations_building_id_fkey"),
        "organisations",
        "buildings",
        ["building_id"],
        ["id"],
        ondelete="cascade",
    )
    op.alter_column(
        "phones",
        "number",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phones",
        "number",
        existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=12),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("organisations_building_id_fkey"), "organisations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("organisations_building_id_fkey"),
        "organisations",
        "activities",
        ["building_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
